### ISSUE TITLE
Video doesn't render on device

### ISSUE THREAD

**Issue by derickito** [KalebKE/VideoCamera#2]
iOS 13.6
Xcode 11.6 & Xcode 12 beta 2
iPhone SE 2020 (Second generation)

Something must've changed on iOS because I only see the white background.

Thanks,

**Comment by KalebKE** [comment]
@derickito 
I haven't worked with iOS video in four years. I have no idea what would have changed and I don't even have the equipment to test this anymore.

I might try a few different videos just to make sure because I would be surprised if much changed.

**Comment by derickito** [comment]
Ok, thanks.

This takes video input from the camera though right? Not a video file? Or did I miss something?

I actually came across your project because I was trying to do the same thing and it didn’t work.

Anyhow thanks for your time.

**Comment by derickito** [comment]
In case anyone else has this problem, I figured out the issue was, sort of. For some reason adding the `AVSampleBufferDisplayLayer` as a sublayer on a view it doesn't seem to work. You need to subclass UIView and override the following properties:

```
override class var layerClass: AnyClass {
     return AVSampleBufferDisplayLayer.self
}
    
var videoLayer: AVSampleBufferDisplayLayer {
     return layer as! AVSampleBufferDisplayLayer
}
```

You then use the `videoLayer` as normal
